/**
 * Room Create Modal
 *
 * Modal for creating a new watch party room
 * Shows form, calls API, displays share code on success
 */

'use client'

import { useState } from 'react'
import { X } from 'lucide-react'
import { getTeamAbbreviation as getMlbTeamAbbreviation } from '@/lib/mlb-teams'
import { getTeamAbbreviation as getNflTeamAbbreviation } from '@/lib/nfl-teams'

interface RoomCreateModalProps {
  gameId: string
  homeTeam: string
  awayTeam: string
  gameDate?: string
  onClose: () => void
  onSuccess: (roomId: string, shareCode: string, gameId: string, roomName: string) => void
}

export function RoomCreateModal({
  gameId,
  homeTeam,
  awayTeam,
  gameDate,
  onClose,
  onSuccess
}: RoomCreateModalProps) {
  // Room name is auto-generated by the server and NOT editable by users
  const roomName = `${awayTeam} @ ${homeTeam}`

  // Display name with abbreviations and date
  const isNfl = gameId.startsWith('nfl-')
  const getTeamAbbreviation = isNfl ? getNflTeamAbbreviation : getMlbTeamAbbreviation
  const awayAbbr = getTeamAbbreviation(awayTeam)
  const homeAbbr = getTeamAbbreviation(homeTeam)

  const formatGameDate = (isoDate: string): string => {
    try {
      const date = new Date(isoDate)
      const month = date.getMonth() + 1
      const day = date.getDate()
      return `${month}/${day}`
    } catch {
      return ''
    }
  }

  const dateStr = gameDate ? ` - ${formatGameDate(gameDate)}` : ''
  const displayName = `${awayAbbr} @ ${homeAbbr}${dateStr}`

  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)
    setError(null)

    try {
      const response = await fetch('/api/rooms/create', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          gameId,
          name: roomName,
          maxMembers: 10,
          homeTeam,
          awayTeam,
          gameDate
        })
      })

      const data = await response.json()

      if (!response.ok) {
        throw new Error(data.error || 'Failed to create room')
      }

      onSuccess(data.roomId, data.shareCode, data.gameId, data.roomName)

    } catch (err) {
      setError(err instanceof Error ? err.message : 'Something went wrong')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-2xl max-w-md w-full p-6">
        {/* Header */}
        <div className="flex items-center justify-between mb-6">
          <h2 className="text-2xl font-bold text-slate-800 dark:text-slate-100">
            Create Watch Party
          </h2>
          <button
            onClick={onClose}
            className="p-2 hover:bg-slate-100 dark:hover:bg-slate-700 rounded-lg transition-colors"
            aria-label="Close modal"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="block text-sm font-semibold text-slate-700 dark:text-slate-200 mb-2">
              Game
            </label>
            <div className="p-3 bg-blue-50 dark:bg-blue-900/20 rounded-lg">
              <p className="text-sm font-medium text-blue-800 dark:text-blue-200">
                {awayTeam} @ {homeTeam}
              </p>
            </div>
          </div>

          <div>
            <label className="block text-sm font-semibold text-slate-700 dark:text-slate-200 mb-2">
              Room Name
            </label>
            <div className="p-3 bg-slate-100 dark:bg-slate-700/50 rounded-lg border border-slate-200 dark:border-slate-600">
              <p className="text-base font-bold text-slate-900 dark:text-slate-100">
                {displayName}
              </p>
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
                Room names are automatically generated from the game
              </p>
            </div>
          </div>

          {error && (
            <div className="p-3 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg">
              <p className="text-sm text-red-800 dark:text-red-200">{error}</p>
            </div>
          )}

          <div className="flex gap-3 pt-2">
            <button
              type="button"
              onClick={onClose}
              className="flex-1 px-4 py-2.5 border-2 border-slate-300 dark:border-slate-600 rounded-lg font-semibold hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors"
              disabled={loading}
            >
              Cancel
            </button>
            <button
              type="submit"
              className="flex-1 px-4 py-2.5 bg-gradient-to-r from-blue-600 to-blue-700 text-white font-semibold rounded-lg hover:from-blue-700 hover:to-blue-800 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-md hover:shadow-lg"
              disabled={loading}
            >
              {loading ? 'Creating...' : 'Create Room'}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}
